# print('Enter Your Name:')
# Name=input()
# print('Entered Name is :',Name)
# print()
# Name=input('Enter Your Name')
# print('Entered Name:',Name)
# print('Entered Name:',type(Name))

# print()
# value_01=int(input('Enter Your Mobile Number'))
# print('Entered Number:',value_01)
# print('Entered Name:',type(value_01))
# print()
# value_01=float(input('Enter Your Percentage'))
# print('Entered Number:',value_01)
# print('Entered Name:',type(value_01))